import { addCandidate, addEpisode, attachInspirationToEpisode } from "../actions";
import { getJarvisData } from "@/lib/jarvis";
import { attachedInspo, countCandidates, Empty, EpisodeCard, episodeLabel, Input, MixCard, Page, Panel, Shell, Stat, TrackCard } from "@/components/jarvis-ui";

export const dynamic = "force-dynamic";

export default async function EpisodesPage() {
  const { tracks, inspirationSets, episodes } = await getJarvisData().catch(() => ({ tracks: [], inspirationSets: [], episodes: [] }));
  const activeEpisode = episodes.find((episode) => episode.status === "planning") ?? episodes[0];
  const episodeInspo = attachedInspo(activeEpisode) ?? [];
  return <Shell><Page>
    <Panel red className="p-5 sm:p-8"><p className="text-sm font-black uppercase tracking-[.22em] text-black/60">episode workspace</p><h1 className="mt-4 max-w-5xl font-serif text-[4rem] font-black leading-[.82] tracking-[-.08em] text-black sm:text-[7rem]">{episodeLabel(activeEpisode)}</h1><div className="mt-8 grid gap-2 sm:grid-cols-3"><Stat dark value={countCandidates(activeEpisode)} label="candidates" /><Stat dark value={countCandidates(activeEpisode, "selected")} label="selected" /><Stat dark value={episodeInspo.length} label="mix refs" /></div></Panel>
    <div className="mt-3 grid gap-3 xl:grid-cols-3"><Panel className="p-4 sm:p-6"><p className="label">new episode</p><form action={addEpisode} className="mt-5 grid gap-2"><Input name="episode_number" placeholder="episode # optional" /><Input name="title" placeholder="optional name" /><select name="status" className="field"><option value="planning">planning</option><option value="crate_built">crate built</option><option value="recorded">recorded</option><option value="published">published</option></select><button className="button">create</button></form></Panel><Panel className="p-4 sm:p-6"><p className="label">attach inspo</p><form action={attachInspirationToEpisode} className="mt-5 grid gap-2"><select name="episode_id" className="field" required defaultValue={activeEpisode?.id ?? ""}><option value="" disabled>episode</option>{episodes.map((episode) => <option key={episode.id} value={episode.id}>{episodeLabel(episode)}</option>)}</select><select name="inspiration_set_id" className="field" required><option value="">mix</option>{inspirationSets.map((set) => <option key={set.id} value={set.id}>{set.title}</option>)}</select><button className="button">attach</button></form></Panel><Panel className="p-4 sm:p-6"><p className="label">attach track</p><form action={addCandidate} className="mt-5 grid gap-2"><select name="episode_id" className="field" required defaultValue={activeEpisode?.id ?? ""}><option value="" disabled>episode</option>{episodes.map((episode) => <option key={episode.id} value={episode.id}>{episodeLabel(episode)}</option>)}</select><select name="track_id" className="field" required><option value="">track</option>{tracks.map((track) => <option key={track.id} value={track.id}>{track.artist} — {track.title}</option>)}</select><button className="button">candidate</button></form></Panel></div>
    <div className="mt-3 grid gap-3 xl:grid-cols-[.65fr_1.35fr]"><Panel className="p-4 sm:p-6"><p className="label">episodes</p><div className="mt-4 grid gap-2">{episodes.map((episode) => <EpisodeCard key={episode.id} episode={episode} active={episode.id === activeEpisode?.id} />)}{!episodes.length && <Empty text="No episodes yet." />}</div></Panel><div className="grid gap-3"><Panel className="p-4 sm:p-6"><p className="label">mood board for active episode</p><div className="mt-4 grid gap-2 md:grid-cols-2">{episodeInspo.map((set) => <MixCard key={set.id} set={set} compact />)}{!episodeInspo.length && <Empty text="No mixes attached yet." />}</div></Panel><Panel className="p-4 sm:p-6"><p className="label">candidate source pool</p><div className="mt-4 grid gap-2 md:grid-cols-2">{tracks.slice(0,8).map((track) => <TrackCard key={track.id} track={track} />)}{!tracks.length && <Empty text="No tracks yet." />}</div></Panel></div></div>
  </Page></Shell>;
}
