import Link from "next/link";
import type { Episode, InspirationSet, Track } from "@/lib/jarvis";

export function Shell({ children }: { children: React.ReactNode }) {
  return <main className="min-h-screen bg-[#050505] text-[#f4f0e8]"><div className="fixed inset-0 bg-[linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px)] bg-[size:28px_28px]" /><div className="fixed inset-0 bg-[radial-gradient(circle_at_18%_8%,rgba(255,56,38,.18),transparent_24%),radial-gradient(circle_at_88%_18%,rgba(255,199,86,.11),transparent_26%)]" /><div className="relative mx-auto grid min-h-screen max-w-[1800px] lg:grid-cols-[88px_1fr]"><Sidebar />{children}</div></main>;
}

function Sidebar() {
  return <aside className="sticky top-0 z-40 flex h-16 items-center justify-between border-b border-white/15 bg-[#050505]/92 px-4 backdrop-blur-xl lg:h-screen lg:flex-col lg:border-b-0 lg:border-r lg:px-0 lg:py-5"><Link href="/" className="grid size-10 place-items-center border border-white bg-[#f4f0e8] text-xl font-black text-black">SS</Link><nav className="flex gap-2 overflow-x-auto text-[11px] font-black uppercase tracking-[0.18em] lg:grid lg:gap-3 lg:[writing-mode:vertical-rl]"><Link href="/episodes" className="nav">episodes</Link><Link href="/inspo" className="nav">inspo</Link><Link href="/tracks" className="nav">tracks</Link></nav><p className="hidden rotate-180 text-[10px] font-black uppercase tracking-[0.25em] text-white/45 [writing-mode:vertical-rl] lg:block">jarvis / app</p></aside>;
}

export function Page({ children }: { children: React.ReactNode }) { return <section className="px-3 py-3 sm:px-5 lg:px-7 lg:py-5">{children}</section>; }
export function Panel({ children, red = false, className = "" }: { children: React.ReactNode; red?: boolean; className?: string }) { return <section className={`${red ? "panel-red" : "panel"} ${className}`}>{children}</section>; }
export function Label({ children }: { children: React.ReactNode }) { return <p className="label">{children}</p>; }
export function Title({ children }: { children: React.ReactNode }) { return <h1 className="title">{children}</h1>; }
export function Input({ className = "", ...props }: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={`field ${className}`} />; }
export function Empty({ text }: { text: string }) { return <div className="border border-dashed border-white/20 bg-white/[.03] p-4 text-sm leading-6 text-white/50">{text}</div>; }
export function Stat({ value, label, dark }: { value: number | string; label: string; dark?: boolean }) { return <div className={dark ? "border border-black/20 bg-black/10 p-3" : "border border-white/15 bg-white/[.04] p-3"}><p className="font-mono text-3xl font-black">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-[0.18em] opacity-60">{label}</p></div>; }

export function episodeLabel(episode?: Episode | null) { if (!episode) return "No episode yet"; return episode.episode_number ? `Episode ${episode.episode_number}` : `Episode · ${new Date(episode.created_at).toLocaleDateString()}`; }
export function countCandidates(episode?: Episode, status?: string) { const candidates = episode?.jarvis_episode_candidates ?? []; return status ? candidates.filter((candidate) => candidate.status === status).length : candidates.length; }
export function attachedInspo(episode?: Episode) { return episode?.jarvis_episode_inspiration_sets?.map((row) => row.jarvis_inspiration_sets).filter(Boolean) as InspirationSet[] | undefined; }
export function bucketLabel(bucket: string) { return bucket.replace("_", " "); }

export function MixCard({ set, compact }: { set: InspirationSet; compact?: boolean }) { return <a href={set.url} target="_blank" rel="noreferrer" className="block border border-white/15 bg-[#101010] p-4 hover:border-[#ff3826]"><p className="label text-[#ff3826]">{set.source_type}</p><h3 className={compact ? "mt-2 font-serif text-2xl leading-none" : "mt-3 font-serif text-4xl leading-none tracking-[-.04em]"}>{set.title}</h3><p className="mt-2 text-sm text-white/50">{set.artist_or_channel}</p>{!compact && <p className="mt-4 line-clamp-3 text-sm leading-6 text-white/60">{set.flow_notes || set.notes || "no notes yet"}</p>}</a>; }
export function EpisodeCard({ episode, active }: { episode: Episode; active?: boolean }) { return <article className={active ? "border-2 border-[#ff3826] bg-[#ff3826] p-4 text-black" : "border border-white/15 bg-white/[.04] p-4"}><div className="flex items-start justify-between gap-3"><h3 className="font-serif text-3xl leading-none tracking-[-.04em]">{episodeLabel(episode)}</h3><span className="font-mono text-xs font-black uppercase">{episode.status.replace("_", " ")}</span></div>{episode.title && !episode.title.startsWith("Episode ") && <p className="mt-2 text-sm font-bold opacity-70">{episode.title}</p>}<p className="mt-3 text-sm font-bold opacity-70">{countCandidates(episode)} candidates · {countCandidates(episode, "selected")} selected · {attachedInspo(episode)?.length ?? 0} mixes</p></article>; }
export function TrackCard({ track }: { track: Track }) { const tags = track.jarvis_track_tags ?? []; const links = track.jarvis_track_links ?? []; const drops = track.jarvis_picodrops_files ?? []; return <article className="border border-white/15 bg-[#101010] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">{track.artist}</p><h3 className="mt-2 font-serif text-3xl leading-none tracking-[-.04em]">{track.title}</h3></div><span className="border border-white/20 px-2 py-1 text-[10px] font-black uppercase tracking-[.14em] text-[#ff3826]">{bucketLabel(track.rating_bucket)}</span></div>{track.notes && <p className="mt-3 text-sm leading-6 text-white/58">{track.notes}</p>}<div className="mt-4 flex flex-wrap gap-2">{tags.map(({ tag }) => <span key={tag} className="bg-white px-2 py-1 text-[10px] font-black uppercase tracking-[.12em] text-black">{tag}</span>)}{links.map((link) => <a key={link.url} href={link.url} target="_blank" rel="noreferrer" className="bg-[#ff3826] px-2 py-1 text-[10px] font-black uppercase tracking-[.12em] text-black">{link.type}</a>)}{!!drops.length && <span className="bg-[#ffd24a] px-2 py-1 text-[10px] font-black uppercase tracking-[.12em] text-black">PicoDrops</span>}</div></article>; }
